version: 0.2
env:
  secrets-manager:
    SNYKAPI: secrets-name:snyk
phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      # Install Snyk
      - echo Install Snyk
      - curl -Lo ./snyk "https://github.com/snyk/snyk/releases/download/v1.210.0/snyk-linux"
      - chmod -R +x ./snyk
      # Snyk auth
      - ./snyk config set api="$SNYKAPI"
  build:
    commands:
      - echo Build started on `date`
      - ./snyk test
  post_build:
    commands:
      # Take these images and push them to Docker hub
      - echo Pushing the Docker images...
      #- docker push yourname/dkr-scanned-react-container-image
