version: 0.2
env:
  secrets-manager:
    SNYKAPI: secrets-name:snyk
    DOCKER: secrets-name:docker
phases: 
  build: 
    commands: 
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t vishalpranav03/snyk .
      - docker tag vishalpranav03/snyk vishalpranav03/snyk:latest
  post_build: 
    commands: 
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push vishalpranav03/snyk:latest
  pre_build: 
    commands: 
      - echo Logging in to Docker Hub..."
      - docker login --username="vishalpranav03" --password=${DOCKER}


