version: 0.2
env:
  secrets-manager:
   DOCKER: dockerp:docker
   #SNYK: snyk:snyk
phases: 
  build: 
    commands: 
      - echo Build started on `date`
      - echo Building the Docker image
      - docker build -t vishalpranav03/snyk .
      - docker tag vishalpranav03/snyk vishalpranav03/snyk:latest
  post_build: 
    commands: 
      - echo Build completed on `date`"
      - echo Pushing the Docker image..."
      - docker push vishalpranav03/snyk:latest"
  pre_build: 
    commands: 
      - echo Logging in to Docker Hub..."
      - docker login --username="vishalpranav03" --password=$DOCKER
      # Install Snyk
      #- echo Install Snyk
      #- curl -Lo ./snyk "https://github.com/snyk/snyk/releases/download/v1.210.0/snyk-linux"
      #- chmod -R +x ./snyk
      # Snyk auth
      #- ./snyk config set api="$SNYK_AUTH_TOKEN"
