version: 0.2
env:
  secrets-manager:
    SNYKAPI: secrets-name:snyk
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing mocha..
      - npm install -g mocha
  pre_build:
    commands:
      # Install Snyk
      - echo Installing NPM dependencies
      - npm install
      - echo Install Snyk
      - curl -Lo ./snyk "https://github.com/snyk/snyk/releases/download/v1.210.0/snyk-linux"
      - chmod -R +x ./snyk
      # Snyk auth
      - ./snyk config set api="$SNYKAPI"
  build:
    commands:
      - echo Running Snyk
      - ./snyk test
      - echo Build started on 'date'
      - echo Compiling on 'date'
      - mocha index.js
  post_build:
    commands:
      - echo Build complete on 'date'
      
