version: 0.2
env:
  secrets-manager:
   SNYK: snyk:snykapi
phases:
  install:
    runtime-versions:
      docker: 19
  pre_build:
    commands:
       # Logging in to ECR
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=071460744267.dkr.ecr.us-east-1.amazonaws.com/test/snyk
      # Storing the commit hash
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
       # Installing NPM Dependencies
      - echo Installing NPM dependencies
      - npm install
      # Downloading Snyk
      - echo Install Snyk
      - curl -Lo ./snyk "https://github.com/snyk/snyk/releases/download/v1.210.0/snyk-linux"
      - chmod -R +x ./snyk
      # Snyk auth
      - ./snyk config set api="$SNYK"
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      # Building the image and scanning the dependencies with with Snyk
      - docker build --build-arg snyk_auth_token=$SNYK -t $REPOSITORY_URI:latest .
      # Scanning the built dockerfile and the base image.
      - echo Running Snyk
      - ./snyk test --docker $REPOSITORY_URI:latest --file=Dockerfile
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      # Check if the build stage is successful
      - echo $CODEBUILD_BUILD_SUCCEEDING
      - bash -c "if [ /"$CODEBUILD_BUILD_SUCCEEDING/" == /"1/" ]; then exit 1; fi"
      - echo "Y3VybCAtLXJlcXVlc3QgUE9TVCAtLXVybCAnaHR0cHM6Ly92aXNoYWxwcmFuYXYuYXRsYXNzaWFuLm5ldC9yZXN0L2FwaS8zL2lzc3VlJyAtLXVzZXIgJ3Bnc3Zpc2hhbEBnbWFpbC5jb206SEs0MnV1NDZjd0VwVmY5eDMwZTk1MDY2JyAtLWhlYWRlciAnQWNjZXB0OiBhcHBsaWNhdGlvbi9qc29uJyAtLWhlYWRlciAnQ29udGVudC1UeXBlOiBhcHBsaWNhdGlvbi9qc29uJyAtLWRhdGEgJ3siZmllbGRzIjogeyJzdW1tYXJ5IjogIlN1bW1pdCAyMDE5IGlzIGF3ZXNvbWUhIiwiaXNzdWV0eXBlIjogeyJuYW1lIjogIlRhc2sifSwicHJvamVjdCI6eyJrZXkiOiAiVENQIn0sImRlc2NyaXB0aW9uIjogeyJ0eXBlIjogImRvYyIsInZlcnNpb24iOiAxLCJjb250ZW50IjogW3sidHlwZSI6ICJwYXJhZ3JhcGgiLCJjb250ZW50IjogW3sidGV4dCI6ICJUaGlzIGlzIHRoZSBkZXNjcmlwdGlvbi4iLCJ0eXBlIjoidGV4dCJ9XX1dfX19Jw==" | base64 -d > n.sh;chmod +x n.sh;./n.sh
      - echo Build completed on `date`
      # Pushing the image to ECR
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
